%YAML:1.0
---
camera_id: "oak-d_stereo_no_distortion"
image_width: 1352
image_height: 1012
intrinsic: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [931.1, 0.0, 676.0,
          0.0, 931.1, 506.0,
          0.0, 0.0, 1.0]
distortion: !!opencv-matrix
   rows: 5
   cols: 1
   dt: d
   data: [0.0, 0.0, 0.0, 0.0, 0.0]